[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[healthcheck]
path = "/api/health"
port = 3000
timeout = 30
interval = 10
retries = 3


