services:
  - type: web
    name: walmco-web
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
